# DDoS Auswertung

## 0. Foreplay

### Notes:

instead of polars, the polars-lts-cpu package is used, to run on the old CPU's of the mobi8

### Imports

In [1]:
from pathlib import Path
import polars as pl
import matplotlib.pyplot as plt
import pyarrow.parquet as pq

### Global parameters

In [2]:
SERVER_IP = "141.22.28.227"

### external IANA protocol list to convert numbers to names

In [3]:
# read IANA list to convert number to text
lf_pro_nb = (
    pl.scan_csv("data/external/protocol-numbers-1.csv", ignore_errors=True)
      .select("Decimal", "Keyword")
).rename({"Keyword": "ip.proto.name", "Decimal": "ip.proto.num"})
lf_pro_nb.head(10).collect()

shape: (10, 2)
┌──────────────┬───────────────┐
│ ip.proto.num ┆ ip.proto.name │
│ ---          ┆ ---           │
│ i64          ┆ str           │
╞══════════════╪═══════════════╡
│ 0            ┆ HOPOPT        │
│ 1            ┆ ICMP          │
│ 2            ┆ IGMP          │
│ 3            ┆ GGP           │
│ 4            ┆ IPv4          │
│ 5            ┆ ST            │
│ 6            ┆ TCP           │
│ 7            ┆ CBT           │
│ 8            ┆ EGP           │
│ 9            ┆ IGP           │
└──────────────┴───────────────┘

In [4]:
# lf = (
#     lf.join(lf_pro_nb, left_on="ip.proto", right_on="ip.proto.num", how="left")
#     .rename({"ip.proto": "ip.proto.num"})
#     .pipe(lambda lf: lf.select(
#     (cols := lf.collect_schema().names(), cols.insert(5, cols.pop(cols.index("ip.proto.name"))), cols)[-1]
# ))
# )

# lf.head(10).collect()

### Read

In [5]:
lf = pl.scan_parquet("data/interim/ddos_1/batch_1_1000.parquet")

# DDoS Auswertung

## 0. Foreplay

### Notes:

instead of polars, the polars-lts-cpu package is used, to run on the old CPU's of the mobi8

### Imports

In [6]:
from pathlib import Path
import polars as pl
import matplotlib.pyplot as plt
import pyarrow.parquet as pq

### Global parameters

In [7]:
SERVER_IP = "141.22.28.227"

### external IANA protocol list to convert numbers to names

In [8]:
# read IANA list to convert number to text
lf_pro_nb = (
    pl.scan_csv("data/external/protocol-numbers-1.csv", ignore_errors=True)
      .select("Decimal", "Keyword")
).rename({"Keyword": "ip.proto.name", "Decimal": "ip.proto.num"})
lf_pro_nb.head(10).collect()

shape: (10, 2)
┌──────────────┬───────────────┐
│ ip.proto.num ┆ ip.proto.name │
│ ---          ┆ ---           │
│ i64          ┆ str           │
╞══════════════╪═══════════════╡
│ 0            ┆ HOPOPT        │
│ 1            ┆ ICMP          │
│ 2            ┆ IGMP          │
│ 3            ┆ GGP           │
│ 4            ┆ IPv4          │
│ 5            ┆ ST            │
│ 6            ┆ TCP           │
│ 7            ┆ CBT           │
│ 8            ┆ EGP           │
│ 9            ┆ IGP           │
└──────────────┴───────────────┘

In [9]:
# lf = (
#     lf.join(lf_pro_nb, left_on="ip.proto", right_on="ip.proto.num", how="left")
#     .rename({"ip.proto": "ip.proto.num"})
#     .pipe(lambda lf: lf.select(
#     (cols := lf.collect_schema().names(), cols.insert(5, cols.pop(cols.index("ip.proto.name"))), cols)[-1]
# ))
# )

# lf.head(10).collect()

### Read

In [10]:
lf = pl.scan_parquet("data/interim/ddos_1/batch_1_1000.parquet")

## CoAP specific analysis

In [11]:
lf_coap = lf.filter(
    pl.col("coap.version").is_not_null()
).collect()
lf_coap

shape: (51_418_885, 35)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.dat ┆ frame.len ┆ frame.pro ┆ ip.src    ┆ … ┆ coap.resp ┆ coap.resp ┆ coap.payl ┆ source_f │
│ etime     ┆ ---       ┆ tocols    ┆ ---       ┆   ┆ onse_to   ┆ onse_in   ┆ oad_lengt ┆ ile      │
│ ---       ┆ i64       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ h         ┆ ---      │
│ datetime[ ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 218.57.3. ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 179       ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573815  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1335      ┆ eth:ether ┆ 183.141.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 75.241    ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573971  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1219      ┆ eth:ether ┆ 111.50.9. ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 66        ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574021  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1335      ┆ eth:ether ┆ 111.38.22 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 0.83      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574340  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1506      ┆ eth:ether ┆ 122.231.2 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 54.74     ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574506  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 36.141.31 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 17:46:3 ┆           ┆ type:ip:u ┆ .197      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 0.463797  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1335      ┆ eth:ether ┆ 123.233.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 17:46:3 ┆           ┆ type:ip:u ┆ 68.239    ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 0.464234  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 120.237.9 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 17:46:3 ┆           ┆ type:ip:u ┆ .58       ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 0.464291  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1335      ┆ eth:ether ┆ 58.243.56 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 17:46:3 ┆           ┆ type:ip:u ┆ .110      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 0.464400  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1219      ┆ eth:ether ┆ 222.136.4 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 17:46:3 ┆           ┆ type:ip:u ┆ 6.14      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 0.464720  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘